In [ ]:
import pandas as pd
import numpy as np
data_gdynia = pd.read_csv("../data/raw/srodmiescie_raw.csv", sep=";", index_col = 0)
data_gdynia.head()

,osm_id,addr_street,addr_number,grupa_parter,funkcja_parter,grupa_pietra,funkcja_pietra,liczba_kondygnacji,mieszana,rok_budowy_szac,styl_arch,stan_tech,wysokosc_max,zabytek
id,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7.0,NaN,NaN,NaN,NaN,28.8,NaN
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5.0,NaN,NaN,NaN,NaN,23.8,NaN
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17.0,NaN,NaN,NaN,NaN,58.5,NaN
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17.0,NaN,NaN,NaN,NaN,59.4,NaN
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6.0,NaN,NaN,NaN,NaN,31.1,NaN


In [2]:
wys = np.array(data_gdynia.wysokosc_max)
np.isnan(wys)

array([False, False, False, ..., False, False, False], shape=(1241,))

In [3]:
l_kond = np.array(data_gdynia.liczba_kondygnacji)
pow_20m = wys >20
l_kond_max5 = l_kond <5
print((pow_20m & l_kond_max5).sum())
print((pow_20m & l_kond_max5).mean()) # ilość procent

117
0.09427880741337631


and potrzebuje jednej wartości True albo False dla całej tablicy, a numpy nie zgaduje, czy chodzi o „którykolwiek” (.any()), czy „wszystkie” (.all()), więc zgłasza błąd. & działa inaczej: porównuje tablice element po elemencie i nie musi niczego rozstrzygać.

In [4]:
wys_copy = wys.copy()
height_mask = wys_copy >100
height_mask.sum()

wys_copy[height_mask] = np.nan
print(np.isnan(wys_copy).sum())
print(np.isnan(wys).sum())


1
0


In [5]:
pozdzial_klasy = np.where(wys <= 12, 'niski', np.where(wys <=25, 'średni', 'wysoki' ))
np.unique(pozdzial_klasy , return_counts= True)

(array(['niski', 'wysoki', 'średni'], dtype='<U6'), array([237, 631, 373]))

In [6]:
il_kond = data_gdynia.liczba_kondygnacji.to_numpy()
wys_kond = np.where(il_kond > 0 , wys/il_kond, np.nan )
wys_kond_round = np.round(wys_kond, decimals= 2)
data_gdynia.osm_id.iloc[wys_kond_round.argsort(descending=True)][:5]

C:\Users\Dell\AppData\Local\Temp\ipykernel_38320\279734753.py:2: RuntimeWarning: divide by zero encountered in divide
  wys_kond = np.where(il_kond > 0 , wys/il_kond, np.nan )


id
1150    205231795
1174    126325518
846     667867704
71      126117724
795     399194270
Name: osm_id, dtype: int64

In [7]:
wys_kond_round[wys_kond_round.argsort(descending=True)][:5]

array([41.1, 37.8, 37.6, 34.9, 33.9])

In [8]:
arr2d = np.stack([wys, wys_kond], axis = 1)
arr2d


array([[28.8       ,  4.11428571],
       [23.8       ,  4.76      ],
       [58.5       ,  3.44117647],
       ...,
       [47.2       ,         nan],
       [47.1       ,         nan],
       [44.1       ,         nan]], shape=(1241, 2))

In [9]:
arr_mean = np.nanmean(arr2d, axis = 0)

In [10]:
np.nanmean(arr2d,axis = 1)

array([16.45714286, 14.28      , 30.97058824, ..., 47.2       ,
       47.1       , 44.1       ], shape=(1241,))

In [11]:
arr_min = np.nanmin(arr2d,axis = 0)
arr_max = np.nanmax(arr2d, axis = 0)

In [12]:
xnorm = (arr2d - arr_min)/(arr_max - arr_min)
xnorm

array([[0.20268007, 0.07134705],
       [0.16080402, 0.08755992],
       [0.45142379, 0.05444634],
       ...,
       [0.35678392,        nan],
       [0.3559464 ,        nan],
       [0.33082077,        nan]], shape=(1241, 2))

In [13]:
print(np.nanmax(xnorm, axis = 0))
print(np.nanmin(xnorm, axis = 0))

[1. 1.]
[0. 0.]


In [14]:
height_mask = wys_copy >50
print(np.sum(height_mask))

6


In [15]:
more_cond_mask = 
print(np.sum(np.isnan(wys_kond)))
print(np.sum(more_cond_mask))

SyntaxError: invalid syntax (2336783327.py, line 1)

In [ ]:
mask1 = il_kond >= 1
np.sum(mask1)
np.any(mask1)

np.True_

In [ ]:
mask2 = wys > 50
np.any(mask2 & mask1)


np.True_

In [ ]:
arr2d[mask2]

array([[ 58.5       ,   3.44117647],
       [ 59.4       ,   3.49411765],
       [124.        ,   3.44444444],
       [ 57.5       ,   5.22727273],
       [ 63.1       ,  10.51666667],
       [ 50.4       ,   4.58181818],
       [ 50.8       ,          nan]])

In [ ]:
arr2d.sort(axis =0)
arr2d

None